favicon: null
name: Lonn Litchfield
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.5878136
  brandStrength: 0.1875
  lightness: 0.7526882
  brandColors:
    - '#000000'
    - '#fbfbfb'
    - '#9a9a9a'
    - '#0050f6'
    - '#00e0f4'
  rhythmicContrast: 0.3369175
typography_spectrum: 0.4103943
layout_spectrum: 0.3082437
analytics:
  twitter: null
  google: null
  facebook: null
cta:
  bucket: null
  version: null
  domain: null
