name: Lonn Litchfield
favicon: null
layout_spectrum: 0.7865973738953471
typography_spectrum: 0.5286248549818993
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.5140517179388553
  lightness: 0.165331402560696
  saturation: 0.1997698254417628
  rhythmicContrast: 0.4079876937903464
purpose: []
